### ISSUE TITLE
blog post preview with missing whitespace

### ISSUE THREAD

**Issue by toaster** [Scrivito/scrivito_example_app_js#170]
The blog post preview uses a concatenated version of the blog entry's page content. The concatenator (regarding to @dcsaszar it is in src/utils/textExtractFromHtml.js) does not add whitespaces when stripping `<p>` or `<div>` tags.

This leads to missing whitespaces and looks as if the content was broken.

**Comment by dcsaszar** [comment]
This issue becomes visible if the HTML contains non-whitespace separated tags like this:

```html
<p>First paragraph.</p><p>Second paragraph.</p><p>Third paragraph.</p>
```

You can reproduce it with:

* create a new blog post
* add a text widget
* add three lines of text:

```text
First paragraph.
Second paragraph.
Third paragraph.
```

View the blog overview

**Comment by dcsaszar** [comment]
Fixed. Apparently when moving to [Scrivito.extractText](https://www.scrivito.com/js-sdk/extractText) in #262
