### ISSUE TITLE
Tabs in Thumbnail Gallery Widget

### ISSUE THREAD

**Issue by capriosa** [Scrivito/scrivito_example_app_js#173]
Tabs in the Thumbnail Gallery Widget don't filter the images by tag, instead if one click on a Tab the images with this tag are hidden. This is due this line of code:
```
if (currentTag && tags.includes(currentTag)) {
    classNames.push("squeezed");
}
```
Solution:
```
if (currentTag && !tags.includes(currentTag)) {
    classNames.push("squeezed");
}
```

**Comment by apepper** [comment]
Thank you again for reporting!
