### ISSUE TITLE
NPM Security Audit error

### ISSUE THREAD

**Issue by dvogeldev** [Scrivito/scrivito_example_app_js#198]
This occured on a fresh install with repo cloned from GitHub

                       === npm audit security report ===                        
                                                                                
┌──────────────────────────────────────────────────────────────────────────────┐
│                                Manual Review                                 │
│            Some vulnerabilities require your attention to resolve            │
│                                                                              │
│         Visit https://go.npm.me/audit-guide for additional guidance          │
└──────────────────────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Prototype Pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ lodash                                                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=4.17.12                                                    │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ b9a5ee7f87d612320db5571b76b7f140b21b3454c5b98081f5fe8e2d48f… │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ b9a5ee7f87d612320db5571b76b7f140b21b3454c5b98081f5fe8e2d48f… │
│               │ > lodash                                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/1065                            │
└───────────────┴──────────────────────────────────────────────────────────────┘
found 1 high severity vulnerability in 15550 scanned packages
  1 vulnerability requires manual review. See the full report for details.

**Comment by dcsaszar** [comment]
@dvogeldev Thanks for the report. We‘ll have a look.
