### ISSUE TITLE
Prerendering result is incomplete

### ISSUE THREAD

**Issue by dcsaszar** [Scrivito/scrivito_example_app_js#3]
Open https://scrivito-example.netlify.com/notincache

### Expected

a pre-rendered 404 page

### Actual

only the loading screen is "pre-rendered" 😿 

### Notes

IE11 is fine, so we have to dig out the SWAT debugging tools ⚒

**Comment by phorsuedzie** [comment]
Firefox shows the `OOOPS` jeep currently (my first visit there).
