### ISSUE TITLE
fs-extra requires node 9, but .nvmrc has version 8

### ISSUE THREAD

**Issue by gorgos** [Scrivito/scrivito_example_app_js#301]
Great job with that example app, I just started using it again. It's awesome! Greetings to all of you from quarantine on the other side of the world. 😉 

One issue I found is that the upgrade in https://github.com/Scrivito/scrivito_example_app_js/commit/e817f2a32ef537a633a27d825188e0f585c4a641 requires node version 9+, but the .nvmrc still sets the version to node 8 which results in the prerender command failing.

**Comment by apepper** [comment]
Hi @gorgos.

Good to hear you! And thank you, that you're still enjoying Scrivito 😃.

Are you still in New Zealand?

Greeting from Berlin,
Alex

**Comment by gorgos** [comment]
@apepper Yep, still in New Zealand with a permanent residency now. 😱 Let's see how long I can last here.

@Scrivito: Really loving the attention to detail of the example app. Also noticed a few new cool features of the SDK! I have now switched my blog to Scrivito: https://soliditydeveloper.com/. Should have done that from the beginning. 😅

**Comment by apepper** [comment]
That is great to hear. Thank you for your feedback.
