### ISSUE TITLE
Contact form design broken

### ISSUE THREAD

**Issue by gorgos** [Scrivito/scrivito_example_app_js#302]
Minor issue, but the contact form box for the message goes all the way through the label:

![image](https://user-images.githubusercontent.com/659390/79037656-9565b800-7c2f-11ea-878e-092f81ef1f36.png)

This is how it looks on Chrome and Safari, on Firefox it looks correct.

**Comment by agessler** [comment]
For me only broken in Chrome.. fix is on the way.
