### ISSUE TITLE
Links in Blog Overview Widgets don't adjust color according to background-image

### ISSUE THREAD

**Issue by MaxWeiland** [Scrivito/scrivito_example_app_js#382]
When using the `BlogOverviewWidget` with a background-image selected, the font of the links don't adjust their color.

<img width="697" alt="Bildschirmfoto 2021-04-15 um 12 29 12" src="https://user-images.githubusercontent.com/51741558/114856770-ca2ec100-9de7-11eb-98b5-67191428fabb.png">
<img width="498" alt="Bildschirmfoto 2021-04-15 um 12 40 16" src="https://user-images.githubusercontent.com/51741558/114856780-cf8c0b80-9de7-11eb-9886-cf9e2f21657a.png">

When the Widget is wrapped inside a section, the text is not displayed correctly. It seems to adjust to the color of the background image, not the color of the section. Although I am not sure the widget is supposed to be used that way. 

<img width="1128" alt="Bildschirmfoto 2021-04-15 um 12 44 34" src="https://user-images.githubusercontent.com/51741558/114857661-d23b3080-9de8-11eb-9963-acfc16ed523e.png">

The color of the font seems to be controlled by the css-class `.bg-dark-image`

**Comment by agessler** [comment]
@MaxWeiland I did a fix.. https://github.com/Scrivito/scrivito_example_app_js/pull/389
