### ISSUE TITLE
'Promise' is undefined in IE11

### ISSUE THREAD

**Issue by dcsaszar** [Scrivito/scrivito_example_app_js#388]
Currently, the Example App doesn't run in IE11 with `npx webpack serve --env production`:

```
'Promise' is undefined
```

If I add `import "core-js/modules/es.promise";` to `src/polyfills.js`, it works.

### Discussion

Maybe we should get rid of the manually maintained polyfills, in favor of https://github.com/facebook/create-react-app/blob/master/packages/react-app-polyfill/README.md#supporting-internet-explorer.

The drawback: the gzipped bundle would be 4.5 K larger. 😿

**Comment by apepper** [comment]
Does it also not work on the compiled assets? So far we only had the requirement, that the compiled example app needs to support IE11, but not in dev mode.

**Comment by dcsaszar** [comment]
Compiled has the same behavior as prod serve.

Only dev serve is ok not to work on IE11.

**Comment by dcsaszar** [comment]
FYI this is still an issue
![image](https://user-images.githubusercontent.com/986170/145160249-339b21fa-f091-4e21-87b7-ef9478b954ad.png)
