### ISSUE TITLE
Prerender ist not compatible with last webpack (5.38.1) module

### ISSUE THREAD

**Issue by cbou** [Scrivito/scrivito_example_app_js#399]
Steps:
1. Delete the file `package-lock.json`
2. Run `npm install`
3. Run `SCRIVITO_ORIGIN=http://localhost:8080 npm run prerender`

You will get an error in the buildNode/prerender_content.js 

```
TypeError: Cannot read property 'call' of undefined
```

**Comment by dcsaszar** [comment]
Bisecting outcome: the first bad version is https://github.com/webpack/webpack/releases/tag/v5.24.1

**Comment by cbou** [comment]
Thanks :) I lost too much time on this issue to do the bisect :D
