### ISSUE TITLE
New Build - Uncaught type error

### ISSUE THREAD

**Issue by dvogeldev** [Scrivito/scrivito_example_app_js#72]
**Error msg:**
> index.js:1
> 
>  Uncaught TypeError: Super expression must either be null or a function, not undefined
>     at index.js:1
>     at index.js:1
>     at t.a (index.js:1)
>     at new e (index.js:1)
>     at Function.value (index.js:1)
>     at Object.<anonymous> (index.js:1)
>     at n (index.js:1)
>     at Object.<anonymous> (index.js:1)
>     at n (index.js:1)
>     at Object.<anonymous> (index.js:1)
## Steps taken
1. Git clone repo
2. ```npm install```
3. Add .env file
4. ```npm run-script build```
5. Upload build.zip to instance
6. View installed file https://5b2d0a653672df57503fdfed--secure-raspberry-scrivito-0621.netlify.com/
## Insights
The site works fine on my localhost. Problem occurs when I upload the build.zip to the dashboard and view it in the temporary netlify url. The download zipfile from the dashboard works fine but not the clone of this repo.

Your help greatly appreciated.

**Comment by Agsiegert** [comment]
HI David, 

Looks like there is a mismatch in your package versions causing the problem. Could you try deleting and rebuilding `node_modules` with `rm -rf node_modules`.  Then rerun `npm install` and `npm run build`.  Otherwise, it might be as simple as a typo like .component vs .Component.

**Comment by dvogeldev** [comment]
Thanks, problem solved.
